version: '3.9'
name: tp1
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    networks:
      - testing_net
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CITIES=montreal
    volumes:
      - ./client/config.ini:/config.ini
      - ./.data/dev:/data
    networks:
      - testing_net
    depends_on:
      - server
      
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - N_CITIES=1
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  packet_distributor:
    container_name: packet-distributor
    image: packet-distributor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  weather-filter-1:
    container_name: weather-filter-1
    image: weather-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITIES=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  weather-filter-2:
    container_name: weather-filter-2
    image: weather-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITIES=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

