version: '3.9'
name: tp1
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    networks:
      - testing_net
    healthcheck:
        test: [CMD, curl, -f, http://localhost:15672]
        interval: 10s
        timeout: 5s
        retries: 10


  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CITIES=montreal,toronto,washington
    volumes:
      - ./client/config.ini:/config.ini
      - ./.data/dev:/data
    networks:
      - testing_net
    depends_on:
      - server
    deploy:
      resources:
        limits:
          cpus: '0.70'

  
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - N_CITIES=3
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  packet_distributor1:
    container_name: packet-distributor1
    image: packet-distributor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - FIRST_YEAR_COMPARE=2016
      - SECOND_YEAR_COMPARE=2017
      - CITY_TO_CALC_DISTANCE=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  packet_distributor2:
    container_name: packet-distributor2
    image: packet-distributor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - FIRST_YEAR_COMPARE=2016
      - SECOND_YEAR_COMPARE=2017
      - CITY_TO_CALC_DISTANCE=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  packet_distributor3:
    container_name: packet-distributor3
    image: packet-distributor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - FIRST_YEAR_COMPARE=2016
      - SECOND_YEAR_COMPARE=2017
      - CITY_TO_CALC_DISTANCE=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  packet_distributor4:
    container_name: packet-distributor4
    image: packet-distributor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - FIRST_YEAR_COMPARE=2016
      - SECOND_YEAR_COMPARE=2017
      - CITY_TO_CALC_DISTANCE=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  packet_distributor5:
    container_name: packet-distributor5
    image: packet-distributor:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - FIRST_YEAR_COMPARE=2016
      - SECOND_YEAR_COMPARE=2017
      - CITY_TO_CALC_DISTANCE=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  weather-filter-montreal1:
    container_name: weather-filter-montreal1
    image: weather-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=montreal
      - NUMBER_AVERAGE_DURATION_PROCESSES=2
      - PRECTOT_COND=30
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  weather-filter-montreal2:
    container_name: weather-filter-montreal2
    image: weather-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=montreal
      - NUMBER_AVERAGE_DURATION_PROCESSES=2
      - PRECTOT_COND=30
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  weather-filter-toronto1:
    container_name: weather-filter-toronto1
    image: weather-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=toronto
      - NUMBER_AVERAGE_DURATION_PROCESSES=2
      - PRECTOT_COND=30
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  weather-filter-washington1:
    container_name: weather-filter-washington1
    image: weather-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=washington
      - NUMBER_AVERAGE_DURATION_PROCESSES=2
      - PRECTOT_COND=30
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  weather-filter-washington2:
    container_name: weather-filter-washington2
    image: weather-filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=washington
      - NUMBER_AVERAGE_DURATION_PROCESSES=2
      - PRECTOT_COND=30
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  average-duration-0:
    container_name: average-duration-0
    image: average-duration:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - PROCESS_ID=0
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  average-duration-1:
    container_name: average-duration-1
    image: average-duration:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - PROCESS_ID=1
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  results-collector-average:
    container_name: results-collector-average
    image: results-collector-average:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - NUMBER_AVERAGE_DURATION_PROCESSES=2
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  eof-manager:
    container_name: eof-manager
    image: eof-manager:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - N_PACKET_DISTRIBUTOR=5
      - CITIES=montreal,toronto,washington
      - N_WEATHER_FILTER_PER_CITY=2,1,2
      - N_STATIONS_JOINER_PER_CITY=3,1,2
      - NUMBER_AVERAGE_DURATION_PROCESSES=2
      - N_DISTANCES_JOIN_PARSER=2
      - DISTANCES_JOIN_PARSER_CITY=montreal
      - N_DISTANCE_CALCULATOR=2
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  stations-joiner-montreal1:
    container_name: stations-joiner-montreal1
    image: stations-joiner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  stations-joiner-montreal2:
    container_name: stations-joiner-montreal2
    image: stations-joiner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  stations-joiner-montreal3:
    container_name: stations-joiner-montreal3
    image: stations-joiner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  stations-joiner-toronto1:
    container_name: stations-joiner-toronto1
    image: stations-joiner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=toronto
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  stations-joiner-washington1:
    container_name: stations-joiner-washington1
    image: stations-joiner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=washington
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  stations-joiner-washington2:
    container_name: stations-joiner-washington2
    image: stations-joiner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=washington
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  trips-per-year-montreal:
    container_name: trips-per-year-montreal
    image: trips-per-year:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=montreal
      - FIRST_YEAR_COMPARE=2016
      - SECOND_YEAR_COMPARE=2017
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  trips-per-year-toronto:
    container_name: trips-per-year-toronto
    image: trips-per-year:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=toronto
      - FIRST_YEAR_COMPARE=2016
      - SECOND_YEAR_COMPARE=2017
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  trips-per-year-washington:
    container_name: trips-per-year-washington
    image: trips-per-year:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=washington
      - FIRST_YEAR_COMPARE=2016
      - SECOND_YEAR_COMPARE=2017
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  results-collector-trips-per-year:
    container_name: results-collector-trips-per-year
    image: results-collector-trips-per-year:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - N_CITIES=3
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  distances-join-parser-0:
    container_name: distances-join-parser-0
    image: distances-join-parser:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  distances-join-parser-1:
    container_name: distances-join-parser-1
    image: distances-join-parser:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CITY=montreal
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  distance-calculator-0:
    container_name: distance-calculator-0
    image: distance-calculator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  distance-calculator-1:
    container_name: distance-calculator-1
    image: distance-calculator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  average-distances:
    container_name: average-distances
    image: average-distances:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - MINIMUM_DISTANCE_KM=6
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

